spring:
  application:
    name: payment-service

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

app:
  random-api:
    url: "https://www.random.org"